version: "3"
services:
    database:
        container_name: listerr-database
        image: mongo
        ports:
            - 27017:27017
        volumes:
            - /data/db:/data/db
    frontend:
        container_name: listerr-web
        build:
            context: ./client
            dockerfile: Dockerfile
        image: realvikas/listerr-web
        ports:
            - 3000:3000
        volumes:
            - ./client:/usr/src/app
    backend:
        container_name: listerr-server
        build:
            context: ./server
            dockerfile: Dockerfile
        image: realvikas/listerr-server
        ports:
            - 5000:5000
            - 9229:9229
        env_file:
            - ./server/.env
        volumes:
            - ./server:/usr/src/app
        depends_on:
            - database
