[build]
    base = "packages/client"
    publish = "build"
    command = "yarn build"
    # ignore = "git diff --quiet HEAD^ HEAD packages/server/"
    [build.environment]
        NODE_ENV = "production"
        YARN_VERSION = "1.20.0"
        REACT_APP_BASE_URI = "https://listrrr.herokuapp.com"

# The following redirect is intended for use with most SPAs that handle
# routing internally.
[[redirects]]
    from = "/*"
    to = "/index.html"
    status = 200
