[build]
    base = "."
    publish = "packages/client/build"
    command = "yarn build:client"
    ignore = "git diff --quiet HEAD^ HEAD packages/server/"
    environment = { BASE_URI = "https://listrrr.herokuapp.com" }

# The following redirect is intended for use with most SPAs that handle
# routing internally.
[[redirects]]
    from = "/*"
    to = "/index.html"
    status = 200
[[redirects]]
  from = "https://listrrr.netlify.com"
  to = "https://listrrr.vikasraj.dev"
  status = 301
  force = true