[build]
    base = "."
    publish = "packages/client/build"
    command = "yarn build:client"
    ignore = "git diff --quiet HEAD^ HEAD packages/{client,core}/" 

# The following redirect is intended for use with most SPAs that handle
# routing internally.
[[redirects]]
    from = "/*"
    to = "/index.html"
    status = 200