name: build
on:
    push:
        branches:
            - master
env:
    # DOCKER_BUILDKIT: 1
    GPR_REPO: docker.pkg.github.com/numtostr/listrrr/app
jobs:
    build:
        name: build
        runs-on: ubuntu-latest
        env:
            # COMMIT_HASH: $(echo $GITHUB_SHA | cut -c 1-7)
            COMMIT_HASH: $(git rev-parse --short "$GITHUB_SHA")
        steps:
            - uses: actions/checkout@master

            - name: authentication
              run: |
                  docker login docker.pkg.github.com --username numToStr -p ${{ secrets.LISTRRR_GPR_TOKEN }}

            # - name: Set up Docker Buildx
            #   id: buildx
            #   uses: crazy-max/ghaction-docker-buildx@v1
            #   with:
            #       version: latest

            - name: Building docker image
              run: |
                  docker build --tag $GPR_REPO:latest --file Dockerfile .

              #   docker buildx build --cache-from=$GPR_REPO:latest --build-arg BUILD_INLINE_CACHE=1 --tag $GPR_REPO:latest --file Dockerfile --push .
            # - name: Tagging docker image
            #   run: |
            #       docker tag $GPR_REPO:latest $GPR_REPO:$COMMIT_HASH

            - name: Pushing docker image to GPR
              run: |
                  docker push $GPR_REPO:latest
              #   docker push $GPR_REPO:$COMMIT_HASH
