name: release
on:
    push:
        branches:
            - master
env:
    HUB_USERNAME: numtostr
    APP_NAME: listrrr
jobs:
    docker:
        name: build
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@master

            - name: Prepare
              id: prepare
              run: |
                  echo ::set-output name=version::$(echo $GITHUB_SHA | cut -c 1-7)
                  echo ::set-output name=build_date::$(date -u +'%Y-%m-%dT%H:%M:%SZ')
                  echo ::set-output name=docker_username::$HUB_USERNAME
                  echo ::set-output name=docker_image::$HUB_USERNAME/$APP_NAME

            - name: Set up Docker Buildx
              id: buildx
              uses: crazy-max/ghaction-docker-buildx@v1
              with:
                  version: latest

            - name: Docker login
              env:
                  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
              run: |
                  echo "${DOCKER_PASSWORD}" | docker login -u ${{ steps.prepare.outputs.docker_username }} --password-stdin

            - name: Docker buildx (Release)
              id: buildx
              run: |
                  docker buildx build --cache-from="${{ steps.prepare.outputs.docker_image }}:latest" \
                    --output "type=image,push=false" \
                    --build-arg "BUILD_INLINE_CACHE=1" \
                    --build-arg "VERSION=${{ steps.prepare.outputs.version }}" \
                    --build-arg "BUILD_DATE=${{ steps.prepare.outputs.build_date }}" \
                    --tag "${{ steps.prepare.outputs.docker_image }}:${{ steps.prepare.outputs.version }}" \
                    --tag "${{ steps.prepare.outputs.docker_image }}:latest" \
                    --file Dockerfile .

            - name: Heroku Login
              uses: actions/heroku@master
              with:
                  args: container:login
              env:
                  HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
            - name: Heroku push
              uses: actions/heroku@master
              with:
                  args: container:push web -a $APP_NAME
              env:
                  HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
            - name: Heroku Release
              uses: actions/heroku@master
              with:
                  args: container:release web -a $APP_NAME
              env:
                  HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
