name: listrrr
on:
    push:
        branches:
            - master
    pull_request:
        branches:
            - master
jobs:
    installation:
        name: react-install-n-build
        runs-on: ubuntu-latest
        strategy:
            matrix:
                node-version: [10.x]
        steps:
            - uses: actions/checkout@master
            - name: Using Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@master
              with:
                  node-version: ${{ matrix.node-version }}
            - name: npm install & build
              run: |
                  npm i --prefix client
                  npm run build --prefix client
    build:
        needs: [installation]
        name: docker-image-build
        runs-on: ubuntu-latest
        steps:
            - name: Heroku Login
              uses: actions/heroku@master
              with:
                  args: container:login
              env:
                  HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
            - name: Docker Build
              run: docker build . --file Dockerfile --tag listrrr:$(date +%s)
            - name: Heroku Push
              uses: actions/heroku@master
              with:
                  args: container:push -a listrrr web
              env:
                  HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
            - name: Heroku Release
              uses: actions/heroku@master
              with:
                  args: container:release -a listrrr web
              env:
                  HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
                  # run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
# action "login" {
#   uses = "actions/heroku@master"
#   args = "container:login"
#   secrets = ["HEROKU_API_KEY"]
# }

# action "push" {
#   uses = "actions/heroku@master"
#   needs = "login"
#   args = "container:push -a calm-fortress-1234 web"
#   secrets = ["HEROKU_API_KEY"]
# }

# action "release" {
#   uses = "actions/heroku@master"
#   needs = "push"
#   args = "container:release -a calm-fortress-1234 web"
#   secrets = ["HEROKU_API_KEY"]
# }
