name: release
on:
    push:
        branches:
            - master
env:
    HEROKU_APP: listrrr
jobs:
    deploy:
        name: deployment-heroku
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@master

            - name: Heroku Login
              run: heroku container:login
              env:
                  HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}

            - name: Heroku push
              run: heroku container:push web -a $HEROKU_APP
              env:
                  HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}

            - name: Heroku Release
              run: heroku container:release web -a $HEROKU_APP
              env:
                  HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
