name: listrrr-build
on:
    pull_request:
        branches:
            - master
env:
    APP_NAME: listrrr
jobs:
    build:
        name: build-docker
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@master
            - name: Build the Docker image
              run: docker build --rm --file Dockerfile --tag $APP_NAME .
